services:
  ollama-server:
    build:
      context: ollama/
    container_name: ollama
    networks:
      - ollama-network
    volumes:
      - .data:/root/.ollama

  fastapi-proxy:
    build:
      context: fastapi-proxy/
    container_name: fastapi-ollama-proxy
    networks:
      - ollama-network
    volumes:
      - ./fastapi-proxy/:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

networks:
  ollama-network:
    driver: bridge